server:
  port: 8090


spring:
  application:
    name: payment-demo

  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy:MM:dd HH:mm:ss  # 定义json的时间格式
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_demo?CharacterEncoding=utf87serverTimeZone=GMT%2B8&useUnicode=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql日志
  mapper-locations: classpath:com/example/mapper/xml/*.xml #配置xml文件的地址

logging:
  level:
    root: info
